### ISSUE TITLE
Creating an issue with all the changes that I can think off

### ISSUE THREAD

**Issue by nixypanda** [garimaarorashuttl/hello-world-python#1]
## pythonpackage.yml
```
        python-version: [3.7]
```
I think we should test against 3.8 as well.

`if [ -f requirements.txt ]; then pip install -r requirements.txt; fi`
We don't really use requirements file, we have stuff in setup.py. So the following commands should work.
```
pip install # install prod deps
pip install ".[test]" # installs dev deps
```

Opinion: flake8 linting should be enabled by default to throw errors everywhere, and we should also use flake-annotations, which forces you to add type hints everywhere. 
i.e. that would be the default way to do this and then you can modify it later on. So you will need to add something like this
`python -m pip install --upgrade black flake8 flake8-annotations`
`python -m flake8 . --show-source`

Also include black in the pipeline which executes like
`python -m black --check .`

Also let's fail if coverage is not at a certain point. 
`python -m pytest --cov=<module_name> --cov-fail-under=85 -m 'not integration'`

**Comment by nixypanda** [comment]
Flake8 config to use. Add the following section to setup.cfg
```cfg
[flake8]
max-line-length =
    # Black defaults to this
    88
ignore =
    # Conflicts with black formatting
    E203,
    # Black formats without forcing strings or continous strings
    # Which flake8 lacks
    E501,
    # Missing type annotation for self in method, cls in classmethod
    ANN101, ANN102,
    # Missing type annotation for *args and **kwargs respectivly
    ANN002, ANN003
suppress-none-returning = True
```

**Comment by nixypanda** [comment]
Example of dependabot config - https://github.com/Shuttl-Tech/evicter/blob/master/.dependabot/config.yml
```yml
version: 1
update_configs:
  - package_manager: python
    directory: /
    update_schedule: live # live is for testing, we should use something else like `weekly`
    target_branch: master
    automerged_updates:
        - match:
            dependency_type: development
            update_type: semver:minor
        - match:
            dependency_type: production
            update_type: semver:patch
```
